version: '3.4'

services:
  swallow.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:54828
    ports:
      - "54828:54828"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - swallow.db

  swallow.client:
    ports:
      - "80:80"

  swallow.db:
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
      - "1434:1434"
    volumes: [
        peta-db-volume:/var/opt/mssql
    ]

