version: '3.4'

services:
  swallow.client:
    image: ${DOCKER_REGISTRY-}swallowclient
    build:
      context: .
      dockerfile: swallow-client/Dockerfile

  swallow.webapi:
    image: ${DOCKER_REGISTRY-}swallowwebapi
    build:
      context: .
      dockerfile: Swallow.WebApi/Dockerfile

  swallow.db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
